REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER(10,0)','No',null,1,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('F_NAME','VARCHAR2(100 BYTE)','Yes',null,2,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('L_NAME','VARCHAR2(100 BYTE)','Yes',null,3,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('AGE','NUMBER(4,0)','Yes',null,4,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PHONE','NUMBER(10,0)','Yes',null,5,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ADDRESS','VARCHAR2(200 BYTE)','Yes',null,6,null);
