REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('ID','NUMBER(10,0)','Yes',null,1,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('MARK','VARCHAR2(100 BYTE)','Yes',null,2,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('OVENVOLUME','VARCHAR2(10 BYTE)','Yes',null,3,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('COLOUR','VARCHAR2(100 BYTE)','Yes',null,4,null);
Insert into EXPORT_TABLE (COLUMN_NAME,DATA_TYPE,NULLABLE,DATA_DEFAULT,COLUMN_ID,COMMENTS) values ('PRICE','NUMBER(38,0)','Yes',null,5,null);
